language: python
sudo: required
dist: jammy
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
env:
  - FLASK=3.0.0
  - FLASK=2.3.3
  - FLASK=2.2.5
  - FLASK=2.1.3
  - FLASK=2.0.3
  - FLASK=1.1.4
  - FLASK=1.0.4
install:
  - pip install Flask==$FLASK
  - pip install -r dev_requirements.txt
script: python setup.py test
